---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seafile.fullname" . }}
  labels: {{ include "seafile.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: "None"
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
{{- if .Values.seafile.webdav.enabled }}
  - port: 8080
    targetPort: http-webdav
    protocol: TCP
    name: http-webdav
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "seafile.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.memcached.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  type: ExternalName
  externalName: "{{ .Release.Name }}-memcached.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
{{- else if ne .Values.memcached.serviceFqdn "memcached" }}
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  type: ExternalName
  externalName: "{{ .Values.memcached.serviceFqdn }}"
{{- end }}
